### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nerdysandy**
Sheeeeevaaammm merge it!

### CODE REVIEW

**Comment by shivamMg** [comment]
Merged!

**Comment by shivamdixit** [comment]
@nerdysandy did you add a space or something?

**Comment by Dawny33** [comment]
What was the diff exactly?

**Comment by nerdysandy** [comment]
@shivamdixit First I thought it was @shivamMg but then I saw that photo :🤦‍♀️

Meet my friends, @shivamdixit and @Dawny33 ...I don't know if they're pulling my leg or they really don't know how to use Github  😕 But here is what I changed: https://screencast.com/t/kcSu23ukbI

**Comment by shivamMg** [comment]
@shivamdixit @Dawny33 It's a grammar fix. I requested her to create a PR since she pointed it out. Stop bugging people.

**Pull request merged**
